FROM python:3.10

RUN apt-get update && apt-get install -y libhdf5-dev && apt-get install -y cron

WORKDIR /app

RUN mkdir -p /app/data
RUN mkdir -p /app/src/scripts 
RUN mkdir -p /app/src/config
RUN mkdir -p /app/src/utils
RUN touch /app/data/cron.log && chmod 666 /app/data/cron.log

COPY ../requirements/requirements_scripts.txt /app

# Copier les fichiers utiles
COPY ../src/__init__.py /app/src
COPY ../src/config /app/src/config
COPY ../src/utils /app/src/utils
COPY ../src/scripts /app/src/scripts

RUN pip install -r requirements_scripts.txt

# Copier le fichier crontab et l'ajouter au cron
COPY ../scripts/monitoring/crontab_docker /etc/cron.d/crontab
RUN chmod 0644 /etc/cron.d/crontab

ENV PYTHONPATH "${PYTHONPATH}:/app/src"
# Démarrer cron et attendre que le fichier de log existe avant de lancer tail
CMD python src/utils/utils_folders_init.py && service cron start && crontab /etc/cron.d/crontab && touch /app/data/cron.log && tail -f /app/data/cron.log
