# Utiliser l'image MLflow v2.15.1 comme base
FROM ghcr.io/mlflow/mlflow:v2.15.1
RUN echo "MLFlow Docker"

WORKDIR /mlflow

RUN mkdir -p /app/data
RUN mkdir /app/data/mlruns

# Exposer le port utilisé par MLflow (par défaut 5000)
EXPOSE 8090

# Définir la commande de démarrage pour MLflow
CMD mlflow server --backend-store-uri file:/app/data/mlruns --host 0.0.0.0 --port 8090
#CMD ["mlflow", "server", "--backend-store-uri", "file:/app/data/mlruns", "--host", "0.0.0.0", "--port", "8090"]