services:
  mlflow:
    build:
      context: ..
      dockerfile: docker-compose/Dockerfile_MLFlow
      #image: mlflow:latest
    container_name: mlflow
    ports:
      - "8090:8090"
    volumes:
      - main_volume:/mlflow
      - shared_data:/app/data
volumes:
  main_volume:
  logs:
  shared_data: