services:
  user_api:
    image: opelliusai/user_api:latest
    container_name: user_api
    ports:
      - "8081:8081"
    volumes:
      - main_volume:/app/volume_data
      - logs:/var/log
      - shared_data:/app/data
  admin_api:
    image: opelliusai/admin_api:latest
    container_name: admin_api
    ports:
      - "8082:8082"
    volumes:
      - main_volume:/app/volume_data
      - logs:/var/log
      - shared_data:/app/data
  monitoring_api:
    image: opelliusai/monitoring_api:latest
    container_name: monitoring_api
    ports:
      - "8083:8083"
    volumes:
      - main_volume:/app/volume_data
      - logs:/var/log
      - shared_data:/app/data
  mlflow:
    image: opelliusai/mlflow:latest
    container_name: mlflow
    ports:
      - "8090:8090"
    volumes:
      - main_volume:/mlflow
      - shared_data:/app/data
  streamlit:
    image: opelliusai/streamlit:latest
    container_name: streamlit
    ports:
      - "8084:8084"
    volumes:
      - main_volume:/app/volume_data
      - logs:/var/log
      - shared_data:/app/data
  streamlit_pres:
    image: opelliusai/streamlit_pres:latest
    container_name: streamlit_pres
    ports:
      - "8085:8085"
    volumes:
      - main_volume:/app/volume_data
      - logs:/var/log
      - shared_data:/app/data  
volumes:
  main_volume:
  logs:
  shared_data: