FROM debian:stable-slim

WORKDIR /etc/prometheus

RUN set -ex && apt-get update -y \
    && apt-get install wget -y

RUN wget "https://github.com/prometheus/prometheus/releases/download/v2.26.0/prometheus-2.26.0.linux-amd64.tar.gz"

RUN tar -xzf prometheus-2.26.0.linux-amd64.tar.gz \
    && rm -rf prometheus-2.26.0.linux-amd64.tar.gz \
    && mv prometheus-2.26.0.linux-amd64/* /etc/prometheus \
    && rm -rf prometheus-2.26.0.linux-amd64 \
    && mv /etc/prometheus/prometheus /usr/local/bin/

RUN wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz \
    && tar -xvf node_exporter-1.0.1.linux-amd64.tar.gz \
    && mv node_exporter-1.0.1.linux-amd64 /usr/local/bin/node_exporter \
    && rm node_exporter-1.0.1.linux-amd64.tar.gz

EXPOSE 8091
EXPOSE 9100

#ENTRYPOINT ["/usr/local/bin/prometheus"]

#CMD ["--config.file=/etc/prometheus/prometheus.yml"]
CMD /usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml & /usr/local/bin/node_exporter/node_exporter