services:
  monitoring_api:
    build:
      context: ..
      dockerfile: docker-compose/Dockerfile_monitoring_api
    image: monitoring_api:latest
    container_name: monitoring_api
    #environment:
    ports:
      - "8083:8083"
    volumes:
      - ../streamlit_users.json:/app/data/streamlit_cache/streamlit_users.json
      - main_volume:/app/volume_data
      - logs:/var/log
      - shared_data:/app/data
volumes:
  main_volume:
  logs:
  shared_data:
  