FROM debian:buster-slim

ENV GRAFANA_VERSION="11.2.0" 

RUN apt-get update && \
    apt-get install -y \
    wget \
    adduser \
    libfontconfig1 \
    && rm -rf /var/lib/apt/lists/*

RUN wget  https://dl.grafana.com/enterprise/release/grafana-enterprise-${GRAFANA_VERSION}.linux-amd64.tar.gz && \
    tar -zxvf grafana-enterprise-${GRAFANA_VERSION}.linux-amd64.tar.gz && \
    mv grafana-v${GRAFANA_VERSION} /usr/share/grafana && \
    rm grafana-enterprise-${GRAFANA_VERSION}.linux-amd64.tar.gz
    
RUN mkdir -p /var/lib/grafana /etc/grafana /var/log/grafana && \
    adduser --system --no-create-home --group grafana && \
    chown -R grafana:grafana /var/lib/grafana /etc/grafana /var/log/grafana

# Exposer le port par défaut de Grafana
EXPOSE 8092

# Définir l'utilisateur Grafana
USER grafana

# Commande d'exécution pour lancer Grafana
CMD ["/usr/share/grafana/bin/grafana-server", "--homepath=/usr/share/grafana", "--config=/etc/grafana/grafana.ini", "cfg:default.paths.logs=/var/log/grafana", "cfg:default.paths.data=/var/lib/grafana", "cfg:default.paths.plugins=/var/lib/grafana/plugins"]
