
FROM python:3.10-slim
RUN echo "MLFlow Docker"
RUN apt-get update && apt-get install -y libhdf5-dev

WORKDIR /app

COPY ../requirements/requirements_mlflow.txt /app

RUN mkdir -p /app/data
RUN mkdir /app/data/mlruns

RUN pip install -r requirements_mlflow.txt

# Exposer le port utilisé par MLflow (par défaut 5000)
EXPOSE 8090

# Définir la commande de démarrage pour MLflow
#CMD mlflow server --backend-store-uri file:/app/data/mlruns --host 0.0.0.0 --port 8090
#CMD ["mlflow", "server", "--backend-store-uri", "file:/app/data/mlruns", "--host", "0.0.0.0", "--port", "8090"]

CMD mlflow server --backend-store-uri file:/app/data/processed/mlruns --default-artifact-root file:/app/data/processed/mlruns --host 0.0.0.0 --port 8090
