services:
  user_api:
    build:
      context: ..
      dockerfile: docker-compose/Dockerfile_user_api
    image: user_api:latest
    container_name: user_api
    ports:
      - "8081:8081"
    volumes:
      - ../streamlit_users.json:/app/data/streamlit_cache/streamlit_users.json
      - main_volume:/app/volume_data
      - logs:/var/log
      - shared_data:/app/data
  admin_api:
    build:
      context: ..
      dockerfile: docker-compose/Dockerfile_admin_api
    image: admin_api:latest
    container_name: admin_api
    ports:
      - "8082:8082"
    volumes:
      - ../streamlit_users.json:/app/data/streamlit_cache/streamlit_users.json
      - ../kaggle.json:/root/.kaggle/kaggle.json
      - main_volume:/app/volume_data
      - logs:/var/log
      - shared_data:/app/data
  monitoring_api:
    build:
      context: ..
      dockerfile: docker-compose/Dockerfile_monitoring_api
    image: monitoring_api:latest
    container_name: monitoring_api
    ports:
      - "8083:8083"
    volumes:
      - ../streamlit_users.json:/app/data/streamlit_cache/streamlit_users.json
      - main_volume:/app/volume_data
      - logs:/var/log
      - shared_data:/app/data
  mlflow:
    build:
      context: ..
      dockerfile: docker-compose/Dockerfile_MLFlow
    image: mlflow:latest
    container_name: mlflow
    ports:
      - "8090:8090"
    volumes:
      - main_volume:/mlflow
      - shared_data:/app/data
  streamlit:
    build:
      context: ..
      dockerfile: docker-compose/Dockerfile_streamlit
    image: streamlit:latest
    container_name: streamlit
    ports:
      - "8084:8084"
    volumes:
      - main_volume:/app/volume_data
      - logs:/var/log
      - shared_data:/app/data
  streamlit_pres:
    build:
      context: ..
      dockerfile: docker-compose/Dockerfile_streamlit_pres
    image: streamlit_pres:latest
    container_name: streamlit_pres
    ports:
      - "8085:8085"
    volumes:
      - main_volume:/app/volume_data
      - logs:/var/log
      - shared_data:/app/data  
  prometheus:
    build:
      context: ..
      dockerfile: docker-compose/Dockerfile_prometheus
    image: prometheus:latest
    container_name: prometheus
    volumes:
      - ../data/prometheus_data/prometheus_dockers.yml:/etc/prometheus/prometheus.yml
    ports:
      - "8091:9090"
volumes:
  main_volume:
  logs:
  shared_data:
  prometheus_data: {}