services:
  user_api:
    build:
      context: ..
      dockerfile: docker-compose/Dockerfile_user_api
    image: user_api:latest
    container_name: user_api
    ports:
      - "8081:8081"
    volumes:
      - ../streamlit_users.json:/app/data/streamlit_cache/streamlit_users.json
      - main_volume:/app/volume_data
      - logs:/var/log
      - shared_data:/app/data
volumes:
  main_volume:
  logs:
  shared_data:
  