services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ../data/prometheus_data/prometheus_dockers.yml:/etc/prometheus/prometheus.yml
    ports:
      - "8091:9090"
volumes:
  prometheus_data: {}