name: Docker Build Monitoring API

on:
  push:
    branches:
      - main

jobs:
  build:
    #runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install docker-compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
 
    - name: Build Monitoring API Docker image
      run: |
          echo "API_KEY=${{ secrets.MONITORING_API_KEY }}" >> .env
          echo '${{ secrets.USERS_JSON }}' > streamlit_users.json
          docker-compose -f docker-compose/docker-compose_monitoring_api.yml build --no-cache

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Tag and push Docker image
      run: |
        docker tag monitoring_api:latest ${{ secrets.DOCKER_USERNAME }}/monitoring_api:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/monitoring_api:latest