name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Construire l'image Docker
      - name: Build Docker image
        run: docker build docker-compose/Dockerfile_airflow -t ${{ secrets.DOCKERHUB_USERNAME }}/airflow:latest

      - name: Tag and push Docker image
        run: |
          docker tag grafana:latest ${{ secrets.DOCKER_USERNAME }}/airflow:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/airflow:latest
