name: Docker Build Prometheus

on:
  push:
    branches:
      - main

jobs:
  build:
    #runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install docker-compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        
    - name: Build Prometheus Docker image
      uses: docker/compose-action@v1.0.0
      with:
        file: docker-compose/docker-compose_prometheus.yml
        push: false
        tags: ${{ github.sha }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Tag and push Docker image
      run: |
        docker tag prometheus:latest ${{ secrets.DOCKER_USERNAME }}/prometheus:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/prometheus:latest