name: Docker Build Admin API

on:
  push:
    branches:
      - main

jobs:
  build:
    #runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Admin API Docker image
      run: |
          echo "API_KEY=${{ secrets.USER_API_KEY }}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
          echo "${{ secrets.KAGGLE_JSON }}" | base64 -d > kaggle.json
          docker-compose -f docker-compose/docker-compose_admin_api.yml build --no-cache

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Tag and push Docker image
      run: |
        docker tag user_api:latest ${{ secrets.DOCKER_USERNAME }}/user_api:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/user_api:latest